# Use the README file as a reference to customize settings.

Book:
  fields:
    default: title, description, user_id
    form: title, description, user_id
  relationships: chapters, taggings, base_tags, tag_taggings, tags
  application: Application
