# Use the README file as a reference to customize settings.

User:
  fields:
    default: email, reset_password_token, reset_password_sent_at, sign_in_count, current_sign_in_at, last_sign_in_at, current_sign_in_ip, last_sign_in_ip, username, role
    form: email, username, role #reset_password_token, reset_password_sent_at, sign_in_count, current_sign_in_at, last_sign_in_at, current_sign_in_ip, last_sign_in_ip
  relationships: books
  application: Application
